version: "3.7"

networks:
  default:
  traefik:
    external: true
    name: ${TRAEFIK_NETWORK}

services:
  redis:
    image: redis
    networks:
      - default

  civicsense_students_be:
    image: ${REGISTRY}/${IMAGETAG}:${GO_REVISION}
    env_file: env_vars/${GO_STAGE_NAME}.env
    environment:
      NODE_ENV: ${GO_STAGE_NAME}
      TASK_BUCKET_NAME: ${TASK_BUCKET_NAME}
      ASSET_BUCKET_NAME: ${ASSET_BUCKET_NAME}
      KMLID: ${KMLID}
      PHONE_NO: ${PHONE_NO}
      ACCESS_KEY: ${ACCESS_KEY}
      SECRETACCESSKEY: ${SECRETACCESSKEY}
      APPLICATION_ARN: ${APPLICATION_ARN}
      REGION: ${REGION}
      COOKIE_NAME: ${COOKIE_NAME}
      SECRET: ${SECRET}
      MONGO_CONNECTION: ${MONGO_CONNECTION}
      REDIS_HOST: ${REDIS_HOST}
      OTP_URL: ${OTP_URL}
      OTP_AUTHKEY: ${OTP_AUTHKEY}
      OTP_TEMPLATE_ID: ${OTP_TEMPLATE_ID}
    networks:
      - traefik
      - default
    deploy:
      replicas: ${NUMBER_REPLICAS}
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: ${SERVICE_RESTART_CONDITION}
        delay: 10s
      labels:
        - traefik.frontend.rule=${TRAEFIK_FRONTEND_HOST}
        - traefik.enable=true
        - traefik.port=${TRAEFIK_PORT}
        - traefik.docker.network=${TRAEFIK_NETWORK}
        # Traefik service that listens to HTTP
        #- traefik.redirectorservice.frontend.entryPoints=http
        #- traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        #- traefik.webservice.frontend.entryPoints=https
